apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-deploy
  name: result-deploy
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30005
  selector:
    app: result-deploy














