apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-deploy
  name: result-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-deploy
  template:
    metadata:
      labels:
        app: result-deploy
    spec:
      containers:
      - image: jamesclarusway/resultserver
        name: result
        ports:
        - containerPort: 80
        env: 
        - name: MYSQL_PASSWORD
          value: "Clarusway_1"
        - name: MYSQL_USER
          value: "clarus"
        - name: MYSQL_DATABASE
          value: "phonebook"
        - name: MYSQL_DATABASE_HOST
          value: mysql-service