apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-deploy
  name: webserver-deploy
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: webserver-deploy
